# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Check In ChinaG

on:
  workflow_dispatch:
  schedule:
    - cron: 17 8-23 * * *

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Checkout running branch
      continue-on-error: true
      id: checkout_run
      run: |
        git checkout run
        git cherry-pick main > /temp/checkin.log
    - name: Resolve cherry pick conflicts
      if: steps.checkout_run.outcome != 'success'
      run: |
        cat /temp/checkin.log | grep 'nothing to commit, working tree clean'
        if [ '$?' = '0' ]; then
          git cherry-pick --abort
        else
          echo 'Force to apply their changes'
          git checkout --theirs .
          git add .
          git cherry-pick --continue
          git push origin run:run
        fi
    - name: Push cherry-picked commits
      if: steps.checkout_run.outcome == 'success'
      run: |
          git push origin run:run
    - name: Check In
      run: |
        ./chinag.py ${{ secrets.CHINAG_USERNAME1 }} ${{ secrets.CHINAG_PASSWORD1 }}
        ./chinag.py ${{ secrets.CHINAG_USERNAME2 }} ${{ secrets.CHINAG_PASSWORD2 }}
    - name: Update the check-in events
      run: |
        ret=$(git status -s)
        if [ -n $ret ]; then
          git add .
          git commit -m 'checked in'
          git push origin run:run
        fi
