# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Check In Chinag

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 17 8-23 * * *

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check In
      run: |
        git checkout --progress --force -B run refs/remotes/origin/run
        ret=$(git cherry-pick main)
        if [ '$?' != '0' ]; then
          echo $ret | grep 'nothing to commit, working tree clean'
          if [ '$?' = '0' ]; then
            git cherry-pick --abort
          else
            echo $ret
            exit 1
          fi
        else
          git push origin run:run
        fi
        ./chinag.py ${{ secrets.CHINAG_USERNAME1 }} ${{ secrets.CHINAG_PASSWORD1 }}
        ./chinag.py ${{ secrets.CHINAG_USERNAME2 }} ${{ secrets.CHINAG_PASSWORD2 }}
        ret=$(git status -s)
        if [ -n $ret ]; then
          git add .
          git commit -m 'checked in'
          git push origin run:run
        fi
