# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Check In Chinag

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      GOOGLE_APPLICATION_CREDENTIALS: "${{ env.HOME }}/service-account-file.json"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install requests firebase-admin
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check In
      run: |
        echo ${{ secrets.FIREBASE_KEY }} | base64 -d > $HOME/service-account-file.json
        ./chinag.py ${{ secrets.CHINAG_USERNAME1 }} ${{ secrets.CHINAG_PASSWORD1 }}
        ./chinag.py ${{ secrets.CHINAG_USERNAME2 }} ${{ secrets.CHINAG_PASSWORD2 }}
